/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_jnitest_NativeClass */

#ifndef _Included_com_example_jnitest_NativeClass
#define _Included_com_example_jnitest_NativeClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_jnitest_NativeClass
 * Method:    jniArrayAvg
 * Signature: (II)Z
 */
JNIEXPORT jint JNICALL Java_com_example_jnitest_NativeClass_jniArrayAvg
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
